// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aavwzsltnkyhixlrhqei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhdnd6c2x0bmt5aGl4bHJocWVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5OTY0NTksImV4cCI6MjA3NTU3MjQ1OX0._sRvMrXu_hqeKV5Iu6ZrbfZvRFVN6ofNMmhwNGUkf3k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});